Repository kyma-project/runtime-watcher, pull requests merged in 2022-07, with the labels that each got.

#11 Update operator dependency
  listener/go.mod
  listener/go.sum
Labels: size/XS, lgtm

#12 Remove log from listener setup
  listener/skr_events_listener.go
Labels: size/XS, lgtm

#14 Add Makefile for pipeline
  listener/Makefile
Labels: lgtm, size/S

#18 refactor: separate kcp and skr watcher
  .gitignore
  kcp-config/gateway.yaml
  kcp/go.mod
  kcp/go.sum
  kcp/pkg/types/event.go
  listener/Makefile
  listener/go.mod
  listener/http_test.go
  listener/skr_events_listener.go
  listener/watcher_event.go
  listener/watcher_event_test.go
  operator/.gitignore
  operator/go.sum
  skr/.dockerignore
  skr/Dockerfile
  skr/Makefile
  skr/PROJECT
  skr/README.md
  skr/config/default/kustomization.yaml
  skr/config/default/manager_auth_proxy_patch.yaml
  skr/config/default/manager_config_patch.yaml
  skr/config/manager/controller_manager_config.yaml
  skr/config/manager/kustomization.yaml
  skr/config/manager/manager.yaml
  skr/config/prometheus/kustomization.yaml
  skr/config/prometheus/monitor.yaml
  skr/config/rbac/auth_proxy_client_clusterrole.yaml
  skr/config/rbac/auth_proxy_role.yaml
  skr/config/rbac/auth_proxy_role_binding.yaml
  skr/config/rbac/auth_proxy_service.yaml
  skr/config/rbac/kustomization.yaml
  skr/config/rbac/leader_election_role.yaml
  skr/config/rbac/leader_election_role_binding.yaml
  skr/config/rbac/role.yaml
  skr/config/rbac/role_binding.yaml
  skr/config/rbac/service_account.yaml
  skr/controllers/configmap_controller.go
  skr/controllers/suite_test.go
  skr/go.mod
  skr/go.sum
  skr/hack/boilerplate.go.txt
  skr/main.go
  skr/pkg/config/config.go
Labels: size/XXL, lgtm

#22 Rework Watcher implementation
  OWNERS
  OWNERS_ALIASES
  README.md
  examples/cm01.yaml
  examples/sample-configmap.yaml
  examples/sample-secret.yaml
  skr/PROJECT
  skr/config/rbac/role.yaml
  skr/controllers/kymaWatch_controller.go
  skr/main.go
  skr/pkg/config/config.go
  skr/pkg/config/values.go
  skr/pkg/factory/factory.go
Labels: size/L, lgtm

#34 Fix `pre-main-kyma-watcher-skr-lint` errors
  skr/controllers/kymaWatch_controller.go
  skr/go.mod
  skr/go.sum
  skr/pkg/config/config.go
Labels: size/L, lgtm

#24 Enhance listener implementation
  kcp/Makefile
  kcp/pkg/listener/skr_events_listener.go
  kcp/pkg/listener/watcher_event.go
Labels: size/M, lgtm
