Repository kyma-project/runtime-watcher, pull requests merged in 2022-10, with the labels that each got.

#84 enhance error log
  skr/internal/handler.go
Labels: lgtm, size/S

#85 Enhance error log
  skr/internal/handler.go
Labels: size/XS, lgtm

#86 refactor: remove KCP watcher
  kcp/.dockerignore
  kcp/.golangci.yaml
  kcp/Dockerfile
  kcp/Makefile
  kcp/PROJECT
  kcp/api/v1alpha1/groupversion_info.go
  kcp/api/v1alpha1/watcher_types.go
  kcp/api/v1alpha1/zz_generated.deepcopy.go
  kcp/config/crd/bases/operator.kyma-project.io_watchers.yaml
  kcp/config/crd/kustomization.yaml
  kcp/config/crd/kustomizeconfig.yaml
  kcp/config/crd/patches/cainjection_in_watchers.yaml
  kcp/config/crd/patches/webhook_in_watchers.yaml
  kcp/config/default/kustomization.yaml
  kcp/config/default/manager_auth_proxy_patch.yaml
  kcp/config/default/manager_config_patch.yaml
  kcp/config/manager/controller_manager_config.yaml
  kcp/config/manager/kustomization.yaml
  kcp/config/manager/manager.yaml
  kcp/config/prometheus/kustomization.yaml
  kcp/config/prometheus/monitor.yaml
  kcp/config/rbac/auth_proxy_client_clusterrole.yaml
  kcp/config/rbac/auth_proxy_role.yaml
  kcp/config/rbac/auth_proxy_role_binding.yaml
  kcp/config/rbac/auth_proxy_service.yaml
  kcp/config/rbac/kustomization.yaml
  kcp/config/rbac/leader_election_role.yaml
  kcp/config/rbac/leader_election_role_binding.yaml
  kcp/config/rbac/role.yaml
  kcp/config/rbac/role_binding.yaml
  kcp/config/rbac/service_account.yaml
  kcp/config/rbac/watcher_editor_role.yaml
  kcp/config/rbac/watcher_viewer_role.yaml
  kcp/config/samples/component_v1alpha1_watcher_compass.yaml
  kcp/config/samples/component_v1alpha1_watcher_kyma.yaml
  kcp/controllers/assets/istio-test-resources.yaml
  kcp/controllers/suite_test.go
  kcp/controllers/watcher_controller.go
  kcp/controllers/watcher_controller_helper_test.go
  kcp/controllers/watcher_controller_test.go
  kcp/go.mod
  kcp/go.sum
  kcp/hack/boilerplate.go.txt
  kcp/internal/custom/istio_client.go
  kcp/internal/deploy/deploy_suite_test.go
  kcp/internal/deploy/webhook_chart.go
  kcp/internal/deploy/webhook_config.go
  kcp/internal/deploy/webhook_config_test.go
  kcp/main.go
Labels: size/XXL, lgtm

#80 Kustomize manifests for the SKR web-hook
  .gitignore
  skr/kustomize/base/deployment.yaml
  skr/kustomize/base/env/deploy-env-vars.env
  skr/kustomize/base/kustomization.yaml
  skr/kustomize/base/namespace.yaml
  skr/kustomize/base/rbac.yaml
  skr/kustomize/base/service.yaml
  skr/kustomize/base/webhook.yaml
  skr/kustomize/certs/Makefile
  skr/kustomize/certs/ca.json
  skr/kustomize/certs/cfssl-config.json
  skr/kustomize/certs/gen-webhook-secret.sh
  skr/kustomize/certs/skr-cluster.json
  skr/kustomize/overlays/test/deployment.yaml
  skr/kustomize/overlays/test/kustomization.yaml
  skr/kustomize/overlays/test/kustomizeconfig.yaml
  skr/kustomize/overlays/test/webhook.yaml
Labels: size/L, lgtm
