Repository kyma-project/runtime-watcher, pull requests merged in 2022-09, with the labels that each got.

#57 refactor: Dark mode support for README.md
  README.md
  docs/assets/runtime-watcher.drawio.svg
Labels: area/documentation, size/XS, lgtm

#59 Remove Kyma Control loop
  kcp/config/crd/bases/component.kyma-project.io_watchers.yaml
  kcp/controllers/kyma_controller.go
  kcp/controllers/kyma_controller_test.go
  kcp/controllers/suite_test.go
  kcp/main.go
  kcp/pkg/types/event.go
  listener/watcher_event.go
Labels: size/L, lgtm

#60 Upgrade KCP dependency
  listener/go.mod
  listener/go.sum
  listener/watcher_event_test.go
Labels: size/M, lgtm

#61 feat: implement resource watch by configured label(s)
  skr/admissionRequest/mock-request-reference-status.json
  skr/chart/skr-webhook/templates/configmap.yaml
  skr/chart/skr-webhook/templates/deployment.yaml
  skr/chart/skr-webhook/templates/rbac.yaml
  skr/chart/skr-webhook/templates/secret.yaml
  skr/chart/skr-webhook/values.yaml
  skr/go.mod
  skr/go.sum
  skr/internal/assets/configmap.yaml
  skr/internal/handler.go
  skr/internal/handler_suite_test.go
  skr/internal/handler_test.go
  skr/internal/handler_test_helpers_test.go
  skr/internal/test_util/util.go
  skr/internal/types.go
Labels: size/XXL, lgtm

#64 refactor: move watcher event to listener module
  kcp/pkg/types/event.go
  listener/go.mod
  listener/go.sum
  listener/http_test.go
  listener/pkg/types/event.go
  listener/watcher_event.go
  listener/watcher_event_test.go
Labels: size/L, lgtm

#65 Removed tmp internal types
  skr/go.mod
  skr/go.sum
  skr/internal/handler.go
  skr/internal/handler_test.go
  skr/internal/test_util/util.go
  skr/internal/types.go
Labels: size/M, lgtm

#66 refactor: rename component.kyma-project.io => operator.kyma-project.io
  examples/sample-WatcherCR.yaml
  kcp/api/v1alpha1/groupversion_info.go
  kcp/config/crd/bases/operator.kyma-project.io_watchers.yaml
  kcp/config/crd/kustomization.yaml
  kcp/config/crd/patches/cainjection_in_watchers.yaml
  kcp/config/crd/patches/webhook_in_watchers.yaml
  kcp/config/rbac/watcher_editor_role.yaml
  kcp/config/rbac/watcher_viewer_role.yaml
  kcp/config/samples/component_v1alpha1_watcher_compass.yaml
  kcp/config/samples/component_v1alpha1_watcher_kyma.yaml
  kcp/controllers/suite_test.go
  kcp/controllers/watcher_controller.go
  kcp/pkg/deploy/webhook_config_test.go
Labels: size/M, lgtm

#68 Set the Owner as NamespacedName
  listener/http_test.go
  listener/watcher_event.go
  listener/watcher_event_test.go
Labels: lgtm, size/S

#53 Implement new deploy concept for watcher control loop
  .gitignore
  kcp/Dockerfile
  kcp/Makefile
  kcp/api/v1alpha1/watcher_types.go
  kcp/api/v1alpha1/zz_generated.deepcopy.go
  kcp/config/crd/bases/operator.kyma-project.io_watchers.yaml
  kcp/config/manager/kustomization.yaml
  kcp/config/manager/manager.yaml
  kcp/config/rbac/role.yaml
  kcp/config/samples/component_v1alpha1_watcher_compass.yaml
  kcp/config/samples/component_v1alpha1_watcher_kyma.yaml
  kcp/controllers/suite_test.go
  kcp/controllers/watcher_controller.go
  kcp/controllers/watcher_controller_test.go
  kcp/go.mod
  kcp/go.sum
  kcp/pkg/deploy/assets/repositories.yaml
  kcp/pkg/deploy/assets/sample-chart/templates/secret.yaml
  kcp/pkg/deploy/assets/sample-chart/templates/webhook-config.yaml
  kcp/pkg/deploy/assets/sample-chart/templates/zz-variables.yaml
  kcp/pkg/deploy/assets/sample-chart/values.yaml
  kcp/pkg/deploy/webhook_config.go
  kcp/pkg/deploy/webhook_config_test.go
  kcp/pkg/util/watcher_util.go
  listener/go.mod
  listener/go.sum
  skr/chart/skr-webhook/templates/secret.yaml
  skr/chart/skr-webhook/values.yaml
Labels: size/XXL, lgtm

#69 fix: kcp-watcher deploy fixes
  kcp/Dockerfile
  kcp/Makefile
  kcp/pkg/deploy/webhook_config.go
  kcp/pkg/util/watcher_util.go
Labels: size/M, lgtm

#72 upgrade: dependencies and cleanup unused files
  examples/sample-Watcher-ConfigMap.yaml
  examples/sample-WatcherCR.yaml
  examples/sample-secret.yaml
  kcp/api/v1alpha1/watcher_types.go
  kcp/api/v1alpha1/zz_generated.deepcopy.go
  kcp/config/crd/bases/operator.kyma-project.io_watchers.yaml
  kcp/config/samples/component_v1alpha1_watcher_compass.yaml
  kcp/config/samples/component_v1alpha1_watcher_kyma.yaml
  kcp/controllers/watcher_controller_test.go
  kcp/go.mod
  kcp/go.sum
  kcp/pkg/deploy/webhook_config.go
  kcp/pkg/util/watcher_util.go
Labels: size/L, lgtm

#73 feat: E2E integration fine tuning - iteration 1
  kcp/api/v1alpha1/watcher_types.go
  kcp/config/default/manager_auth_proxy_patch.yaml
  kcp/config/manager/kustomization.yaml
  kcp/controllers/watcher_controller.go
  kcp/main.go
  kcp/pkg/deploy/webhook_config.go
  kcp/pkg/deploy/webhook_config_test.go
  kcp/pkg/util/watcher_util.go
  listener/Makefile
  listener/example/Dockerfile
  listener/example/main.go
  listener/example/resources/kcp/deployment.yaml
  listener/example/resources/kcp/watchable_resource_skr.yaml
  listener/example/resources/kcp/watcher_kcp.yaml
  listener/example/resources/skr/crd.yaml
  listener/example/resources/skr/watched_resource.yaml
  listener/go.mod
  listener/go.sum
  listener/pkg/event/http_test.go
  listener/pkg/event/skr_events_listener.go
  listener/pkg/event/watcher_event.go
  listener/pkg/event/watcher_event_test.go
  skr/chart/skr-webhook/templates/deployment.yaml
  skr/chart/skr-webhook/templates/secret.yaml
  skr/chart/skr-webhook/values.yaml
Labels: size/XL, lgtm

#77 docs: README.md and other files
  CODEOWNERS
  NOTICE.md
  README.md
  docs/README.md
  docs/assets/runtime-watcher.drawio.svg
  docs/assets/runtime-watcher.svg
  skr/README.md
Labels: area/documentation, size/L, lgtm

#71 Refactor KCP watcher reconcile loop
  kcp/Dockerfile
  kcp/api/v1alpha1/watcher_types.go
  kcp/controllers/assets/istio-test-resources.yaml
  kcp/controllers/suite_test.go
  kcp/controllers/watcher_controller.go
  kcp/controllers/watcher_controller_helper_test.go
  kcp/controllers/watcher_controller_test.go
  kcp/go.mod
  kcp/go.sum
  kcp/internal/custom/istio_client.go
  kcp/internal/deploy/deploy_suite_test.go
  kcp/internal/deploy/webhook_chart.go
  kcp/internal/deploy/webhook_config.go
  kcp/internal/deploy/webhook_config_test.go
  kcp/main.go
  kcp/pkg/deploy/assets/sample-chart/Chart.yaml
  kcp/pkg/deploy/assets/sample-chart/templates/secret.yaml
  kcp/pkg/deploy/assets/sample-chart/values.yaml
  kcp/pkg/deploy/webhook_config.go
  kcp/pkg/deploy/webhook_config_test.go
  kcp/pkg/resources/gateway.yaml
  kcp/pkg/util/watcher_util.go
Labels: size/XXL, lgtm

#78 feat: remove helm cert generator + https callback support
  skr/cert_config/ca-config.json
  skr/cert_config/ca-csr.json
  skr/chart/skr-webhook/templates/deployment.yaml
  skr/chart/skr-webhook/templates/secret.yaml
  skr/chart/skr-webhook/values.yaml
  skr/internal/handler.go
  skr/internal/handler_suite_test.go
  skr/internal/handler_test.go
  skr/internal/handler_util_test.go
  skr/main.go
Labels: size/L, lgtm
