Repository kyma-project/runtime-watcher, pull requests merged in 2022-08, with the labels that each got.

#36 Enhance watcher CR
  kcp/api/v1alpha1/watcher_types.go
  kcp/api/v1alpha1/zz_generated.deepcopy.go
  kcp/config/crd/bases/component.kyma-project.io_watchers.yaml
Labels: size/L, lgtm

#37 Introduce linter and fix all linting issues
  kcp/.golangci.yaml
  kcp/Makefile
  kcp/api/v1alpha1/groupversion_info.go
  kcp/api/v1alpha1/watcher_types.go
  kcp/config/crd/bases/component.kyma-project.io_watchers.yaml
  kcp/controllers/suite_test.go
  kcp/controllers/watcher_controller.go
  kcp/main.go
  kcp/pkg/listener/http_test.go
  kcp/pkg/listener/skr_events_listener.go
  kcp/pkg/listener/watcher_event.go
  kcp/pkg/listener/watcher_event_test.go
  skr/.golangci.yaml
  skr/Makefile
  skr/controllers/kymaWatch_controller.go
  skr/controllers/suite_test.go
  skr/go.mod
  skr/go.sum
  skr/main.go
  skr/pkg/config/config.go
  skr/pkg/config/values.go
  skr/pkg/factory/factory.go
Labels: size/XL, lgtm

#38 Implement watcher cr control loop
  kcp/api/v1alpha1/watcher_types.go
  kcp/config/crd/bases/component.kyma-project.io_watchers.yaml
  kcp/config/samples/component_v1alpha1_watcher.yaml
  kcp/config/samples/component_v1alpha1_watcher_compass.yaml
  kcp/config/samples/component_v1alpha1_watcher_kyma.yaml
  kcp/controllers/watcher_controller.go
  kcp/go.mod
  kcp/go.sum
  kcp/main.go
  kcp/pkg/resources/gateway.yaml
  kcp/pkg/util/watcher_util.go
Labels: size/XXL, lgtm

#39 Implementation of Kyma control loop
  examples/sample-Watcher-ConfigMap.yaml
  examples/sample-WatcherCR.yaml
  examples/sample-configmap.yaml
  examples/sample-secret.yaml
  kcp/Dockerfile
  kcp/PROJECT
  kcp/api/v1alpha1/groupversion_info.go
  kcp/config/rbac/role.yaml
  kcp/controllers/kyma_controller.go
  kcp/controllers/kyma_controller_test.go
  kcp/controllers/suite_test.go
  kcp/controllers/watcher_controller.go
  kcp/go.mod
  kcp/go.sum
  kcp/main.go
  kcp/pkg/util/watcher_util.go
  skr/Dockerfile
  skr/main.go
Labels: size/XL, lgtm

#41 Adapt Makefile for Image build
  kcp/Makefile
  kcp/api/v1alpha1/groupversion_info.go
  kcp/controllers/watcher_controller.go
  skr/Makefile
Labels: lgtm, size/S

#23 feat: init webhook as SKR kyma-watcher
  kcp/Dockerfile
  skr/Makefile
  skr/go.mod
  skr/go.sum
  skr/webhook/Dockerfile
  skr/webhook/admissionRequest/mock-request-reference.json
  skr/webhook/cert_config/ca-config.json
  skr/webhook/cert_config/ca-csr.json
  skr/webhook/chart/skr-webhook/.helmignore
  skr/webhook/chart/skr-webhook/Chart.yaml
  skr/webhook/chart/skr-webhook/templates/deployment.yaml
  skr/webhook/chart/skr-webhook/templates/secret.yaml
  skr/webhook/chart/skr-webhook/values.yaml
  skr/webhook/internal/assets/configmap.yaml
  skr/webhook/internal/handler.go
  skr/webhook/internal/handler_suite_test.go
  skr/webhook/internal/handler_test.go
  skr/webhook/internal/request.go
  skr/webhook/main.go
  skr/webhook/resource.yaml
Labels: size/XXL, lgtm

#43 Implement deploy skr webhook
  .gitignore
  kcp/.golangci.yaml
  kcp/controllers/kyma_controller_test.go
  kcp/controllers/suite_test.go
  kcp/go.mod
  kcp/go.sum
  kcp/pkg/deploy/assets/repositories.yaml
  kcp/pkg/deploy/assets/sample-chart/Chart.yaml
  kcp/pkg/deploy/assets/sample-chart/templates/secret.yaml
  kcp/pkg/deploy/assets/sample-chart/templates/webhook-config.yaml
  kcp/pkg/deploy/assets/sample-chart/templates/zz-variables.yaml
  kcp/pkg/deploy/assets/sample-chart/values.yaml
  kcp/pkg/deploy/deploy_suite_test.go
  kcp/pkg/deploy/webhook_config.go
  kcp/pkg/deploy/webhook_config_test.go
  kcp/pkg/listener/skr_events_listener.go
Labels: size/XXL, lgtm

#46 feat: Introduce go.work and getter for rest.Config
  go.work
  go.work.sum
  kcp/Makefile
  kcp/controllers/kyma_controller_test.go
  kcp/go.mod
  kcp/go.sum
  skr/.golangci.yaml
  skr/Makefile
  skr/go.mod
  skr/go.sum
  skr/webhook/chart/skr-webhook/templates/deployment.yaml
  skr/webhook/chart/skr-webhook/templates/secret.yaml
  skr/webhook/main.go
Labels: size/L, lgtm

#47 refactor: rename kyma-watcher -> runtime-watcher
  CODEOWNERS
  README.md
  docs/Listener.md
  docs/assets/watcher_workflow_network_arc.svg
  examples/sample-Watcher-ConfigMap.yaml
  kcp/Makefile
  kcp/PROJECT
  kcp/controllers/kyma_controller.go
  kcp/controllers/kyma_controller_test.go
  kcp/controllers/suite_test.go
  kcp/controllers/watcher_controller.go
  kcp/go.mod
  kcp/main.go
  kcp/pkg/deploy/assets/sample-chart/Chart.yaml
  kcp/pkg/deploy/webhook_config.go
  kcp/pkg/deploy/webhook_config_test.go
  kcp/pkg/listener/http_test.go
  kcp/pkg/listener/watcher_event.go
  kcp/pkg/listener/watcher_event_test.go
  kcp/pkg/util/watcher_util.go
  skr/Makefile
  skr/PROJECT
  skr/chart/Chart.yaml
  skr/config/manager/kustomization.yaml
  skr/config/manager/manager.yaml
  skr/controllers/kymaWatch_controller.go
  skr/go.mod
  skr/go.sum
  skr/main.go
  skr/webhook/chart/skr-webhook/Chart.yaml
  skr/webhook/internal/handler.go
  skr/webhook/internal/handler_test.go
  skr/webhook/main.go
Labels: do-not-merge/hold, area/documentation, size/L, lgtm

#52 Introduce kyma module list
  kcp/pkg/types/event.go
  listener/go.mod
  listener/go.sum
  listener/http_test.go
  listener/watcher_event.go
  listener/watcher_event_test.go
Labels: size/M, lgtm

#54 Remove go replace from listener `go.mod` file
  listener/go.mod
  listener/go.sum
Labels: size/L, lgtm

#56 refactor: update architecture and README.md
  README.md
  docs/assets/runtime-watcher.drawio.svg
  docs/assets/watcher_workflow_network_arc.svg
Labels: size/M, area/documentation, lgtm
