Repository kyma-project/runtime-watcher, pull requests merged in 2023-08, with the labels that each got.

#110 Update README.md, add architecture.md and a new diagram
  .gitignore
  README.md
  docs/api.md
  docs/architecture.md
  docs/assets/runtime-watcher.svg
  docs/assets/runtime_watcher_architecture_simplified.svg
  examples/connectivity-proxy-config-manifests.yaml
  listener/example-mtls/kcp/gardener/cert_config/ca-config.json
  listener/example-mtls/kcp/gardener/cert_config/ca-csr.json
  listener/example-mtls/kcp/gardener/certificate.yaml
  listener/example-mtls/kcp/gardener/root-ca.sh
  listener/example-mtls/kcp/istio/istio-installation.sh
  listener/example-mtls/kcp/istio/istio-resources.yaml
  listener/example-mtls/kcp/listener/example-listener.yaml
  listener/example-mtls/kcp/listener/httpbin.yaml
  listener/example-mtls/kcp/listener/main.go
  listener/example-mtls/setup.md
  listener/example-mtls/skr/crd.yaml
  listener/example-mtls/skr/main.go
  listener/example-mtls/skr/watched_resource.yaml
  runtime-watcher/.dockerignore
  runtime-watcher/.golangci.yaml
  runtime-watcher/Dockerfile
  runtime-watcher/Makefile
  runtime-watcher/admissionRequest/mock-request-reference-status.json
  runtime-watcher/admissionRequest/mock-request-reference.json
  runtime-watcher/go.mod
  runtime-watcher/go.sum
  runtime-watcher/internal/handler.go
  runtime-watcher/internal/handler_suite_test.go
  runtime-watcher/internal/handler_test.go
  runtime-watcher/internal/handler_util_test.go
  runtime-watcher/internal/request.go
  runtime-watcher/main.go
Labels: size/XL, area/documentation, lgtm

#123 Prepare for GitHub actions
  listener/.golangci.yaml
  listener/Makefile
  listener/pkg/event/skr_events_listener.go
  runtime-watcher/.golangci.yaml
  runtime-watcher/Makefile
  runtime-watcher/internal/handler.go
  runtime-watcher/internal/handler_util_test.go
  runtime-watcher/main.go
Labels: size/M, lgtm

#124 Add GHA workflows
  .github/pull-request-template.md
  .github/workflows/pull-listener-pkg.yml
  .github/workflows/pull-runtime-watcher.yml
  runtime-watcher/Makefile
Labels: size/M, lgtm

#121 reuse compliance
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
Labels: size/L, lgtm

#126 Fix readme links
  README.md
Labels: size/XS, lgtm

#122 Make TLS mode default
  runtime-watcher/go.mod
  runtime-watcher/internal/handler.go
  runtime-watcher/internal/handler_test.go
  runtime-watcher/internal/types.go
  runtime-watcher/main.go
Labels: size/L, lgtm

#128 Listetener Service Metrics
  listener/pkg/event/skr_events_listener.go
  listener/pkg/metrics/metrics.go
Labels: size/L, lgtm
