Repository kyma-project/runtime-watcher, pull requests merged in 2023-09, with the labels that each got.

#133 remove store incoming request into sidecar
  runtime-watcher/internal/handler.go
  runtime-watcher/internal/request.go
Labels: size/M, lgtm

#136 refactor: Extract server config
  .github/workflows/pull-runtime-watcher.yml
  runtime-watcher/Makefile
  runtime-watcher/go.mod
  runtime-watcher/go.sum
  runtime-watcher/internal/handler.go
  runtime-watcher/internal/handler_suite_test.go
  runtime-watcher/internal/handler_test.go
  runtime-watcher/internal/handler_util_test.go
  runtime-watcher/internal/serverconfig/config.go
  runtime-watcher/internal/serverconfig/config_test.go
  runtime-watcher/internal/types.go
  runtime-watcher/main.go
Labels: size/XXL, lgtm

#138 chore: Add PR title prefix
  .github/workflows/lint-conventional-prs.yml
  runtime-watcher/Dockerfile
Labels: size/XS, lgtm

#137 refactor: Extract request parser
  runtime-watcher/internal/handler.go
  runtime-watcher/internal/handler_suite_test.go
  runtime-watcher/internal/handler_test.go
  runtime-watcher/internal/handler_util_test.go
  runtime-watcher/internal/parser/parser.go
  runtime-watcher/internal/types.go
  runtime-watcher/main.go
Labels: size/L, lgtm
