Repository kyma-project/runtime-watcher, pull requests merged in 2023-10, with the labels that each got.

#139 chore: Handle io reader error
  runtime-watcher/internal/handler.go
Labels: lgtm, size/S

#141 chore: Upgade golang.org/x/text
  listener/go.mod
  listener/go.sum
Labels: lgtm, size/S

#142 chore: Update listener version
  runtime-watcher/go.mod
  runtime-watcher/go.sum
Labels: size/XS, lgtm

#140 feat: Make TLS Mandatory for Runtime Watcher
  runtime-watcher/internal/handler.go
  runtime-watcher/internal/handler_suite_test.go
  runtime-watcher/internal/serverconfig/config.go
  runtime-watcher/internal/serverconfig/config_test.go
  runtime-watcher/internal/tlstest/certificate_provider.go
  runtime-watcher/main.go
Labels: size/L, lgtm

#145 chore: Bump some dependencies
  listener/go.mod
  listener/go.sum
  runtime-watcher/go.mod
  runtime-watcher/go.sum
Labels: size/XXL, lgtm

#144 feat: Introduce goreleaser
  runtime-watcher/.goreleaser.yml
  runtime-watcher/Makefile
  runtime-watcher/hack/release.sh
Labels: size/M, lgtm
