Repository kyma-project/runtime-watcher, pull requests merged in 2023-11, with the labels that each got.

#147 Add explicit watcher version
  runtime-watcher/Dockerfile
  runtime-watcher/Makefile
  runtime-watcher/main.go
Labels: lgtm, size/S

#148 chore(github): Adjust PR title linting config
  .github/workflows/lint-conventional-prs.yml
Labels: size/XS, lgtm

#149 chore: Add dependabot.yaml
  .github/dependabot.yml
Labels: size/M, lgtm

#166 feat: Add release workflow
  .github/workflows/create-release.yaml
  README.md
  docs/how_to_release.md
  runtime-watcher/scripts/release/create_changelog.sh
  runtime-watcher/scripts/release/create_draft_release.sh
  runtime-watcher/scripts/release/get_last_release.sh
  runtime-watcher/scripts/release/get_release_by_tag.sh
  runtime-watcher/scripts/release/publish_release.sh
  runtime-watcher/scripts/release/wait_for_image.sh
Labels: area/documentation, size/L, lgtm
