Repository kyma-project/runtime-watcher, pull requests merged in 2024-12, with the labels that each got.

#441 chore: Bump go ver and CVE alerted pkg
  listener/Dockerfile
  listener/go.mod
  listener/go.sum
  runtime-watcher/Dockerfile
  runtime-watcher/go.mod
  runtime-watcher/go.sum
Labels: size/M, lgtm, cla: yes

#448 chore: Bump sec-scanners-config to target 1.1.8
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#452 fix: Adapt to the updated setup-test-cluster action
  .github/workflows/test-e2e-runtime-watcher.yml
Labels: size/XS, cla: yes

#449 chore: Bump k8s dependecies
  runtime-watcher/go.mod
  runtime-watcher/go.sum
Labels: size/M, lgtm, cla: yes

#454 chore: Bump sec-scanners-config to 1.1.9
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes
