Repository kyma-project/runtime-watcher, pull requests merged in 2024-08, with the labels that each got.

#321 deps: Bump module dependencies from listener and lifecycle-manager
  runtime-watcher/go.mod
  runtime-watcher/go.sum
Labels: lgtm, size/S, cla: yes

#329 fix: Rename watcher CR in E2E test
  runtime-watcher/tests/e2e/watcher_enqueue_test.go
Labels: size/XS, lgtm, cla: yes

#333 docs: Add API Label Info
  docs/api.md
Labels: area/documentation, size/XS, lgtm, cla: yes

#344 chore: Bump go version to 1.22.6
  listener/go.mod
  runtime-watcher/go.mod
Labels: size/XS, lgtm, cla: yes

#342 chore: Bump controller-runtime to 0.19.0 in /listener
  listener/go.mod
  listener/go.sum
Labels: size/M, lgtm, cla: yes

#328 chore: Update sec scanner
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#347 chore: Bump prometheus/client-golang to 1.20.1
  listener/go.mod
  listener/go.sum
  runtime-watcher/go.mod
  runtime-watcher/go.sum
Labels: lgtm, size/S, cla: yes

#351 chore: Bump prometheus/client-golang to 1.20.2
  listener/go.mod
  listener/go.sum
  runtime-watcher/go.mod
  runtime-watcher/go.sum
Labels: lgtm, size/S, cla: yes

#352 chore: Update Lifecycle-Manager dependency in `runtime-watcher` to the latest version
  runtime-watcher/go.mod
  runtime-watcher/go.sum
Labels: size/L, lgtm, cla: yes

#353 chore: Update security scanners config
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#357 chore: Bump testing deps
  runtime-watcher/go.mod
  runtime-watcher/go.sum
Labels: size/L, lgtm, cla: yes
