Repository kyma-project/runtime-watcher, pull requests merged in 2024-06, with the labels that each got.

#295 chore: Align golang to 1.22.4
  listener/go.mod
  runtime-watcher/go.mod
Labels: size/XS, lgtm, cla: yes

#296 chore: Update protecode config to use version 1.0.0
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#302 deps: Upgrade k8s deps to v0.30.2
  runtime-watcher/go.mod
  runtime-watcher/go.sum
Labels: lgtm, size/S, cla: yes

#304 chore: Bump github.com/kyma-project/lifecycle-manager/api to v0.0.0-20240612083628-285c5e099d20
  runtime-watcher/go.mod
  runtime-watcher/go.sum
  runtime-watcher/tests/e2e/utils/utils.go
  runtime-watcher/tests/e2e/watcher_enqueue_test.go
  runtime-watcher/tests/e2e/watcher_metrics_test.go
Labels: size/XL, lgtm, cla: yes
