Repository kyma-project/runtime-watcher, pull requests merged in 2024-10, with the labels that each got.

#391 chore: Allow dependabot monitor github actions
  .github/dependabot.yml
Labels: size/XS, lgtm, cla: yes

#397 chore: Bump go versions to 1.23.2
  listener/Dockerfile
  listener/go.mod
  runtime-watcher/Dockerfile
  runtime-watcher/go.mod
Labels: size/XS, lgtm, cla: yes

#398 fix: Image repo name for releases
  .github/workflows/create-release.yaml
Labels: size/XS, cla: yes

#401 chore: Update image to be scanned
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#404 chore: Decouple build image from e2e
  .github/workflows/build-image.yml
  .github/workflows/create-release.yaml
  .github/workflows/test-e2e-runtime-watcher.yml
Labels: size/M, lgtm, cla: yes

#405 fix: Provide E2E Workflow action with IMAGE_REPO env var
  .github/workflows/test-e2e-runtime-watcher.yml
Labels: size/XS, lgtm, cla: yes

#403 chore: Replace vulnerable `golang.org/x/text` dependency
  listener/.golangci.yaml
  listener/go.mod
  listener/go.sum
  runtime-watcher/.golangci.yaml
  runtime-watcher/go.mod
  runtime-watcher/go.sum
Labels: lgtm, size/S, cla: yes

#406 chore: Update markdown-link-check action
  .github/workflows/lint-markdown-links.yml
Labels: size/XS, lgtm, cla: yes

#407 chore: Fix `golang.org/x/text` vulnerability
  listener/.golangci.yaml
  listener/go.mod
  listener/go.sum
  runtime-watcher/.golangci.yaml
  runtime-watcher/go.mod
  runtime-watcher/go.sum
Labels: size/L, lgtm, cla: yes

#410 chore: Update api and listener dependencies
  runtime-watcher/go.mod
  runtime-watcher/go.sum
Labels: size/M, lgtm, cla: yes

#411 chore: Update runtime-watcher img for code scanner
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#412 chore: Fix Build Image tags
  .github/workflows/build-image.yml
Labels: size/M, lgtm, cla: yes

#422 fix: Add modulectl version arg in setup tools step for E2E Github Action
  .github/workflows/test-e2e-runtime-watcher.yml
Labels: size/XS, cla: yes
