Repository kyma-project/runtime-watcher, pull requests merged in 2024-09, with the labels that each got.

#359 docs: Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS, lgtm, cla: yes

#360 docs: Add mandatory sections to README.md
  README.md
Labels: lgtm, size/S, cla: yes

#361 feat: Add GitHub Action Workflow for Runtime Watcher Image Build
  .github/workflows/build-runtime-watcher.yml
Labels: size/M, lgtm, cla: yes

#362 fix: Update build-runtime-watcher
  .github/workflows/build-runtime-watcher.yml
Labels: lgtm, size/S, cla: yes

#363 fix: Fix Dockerfile path
  .github/workflows/build-runtime-watcher.yml
Labels: size/XS, lgtm, cla: yes

#365 fix: Use github action create release
  .github/scripts/release/create_changelog.sh
  .github/scripts/release/draft_release.sh
  .github/scripts/release/get_release_by_tag.sh
  .github/scripts/release/publish_release.sh
  .github/scripts/release/validate_release_tag.sh
  .github/scripts/release/wait_for_image.sh
  .github/workflows/build-image.yml
  .github/workflows/create-release.yaml
  .github/workflows/test-e2e-runtime-watcher.yml
  runtime-watcher/scripts/release/create_changelog.sh
  runtime-watcher/scripts/release/get_last_release.sh
  runtime-watcher/scripts/release/get_release_by_tag.sh
Labels: size/L, lgtm, cla: yes

#370 fix: Make e2e reuse build image workflow
  .github/workflows/build-image.yml
  .github/workflows/test-e2e-runtime-watcher.yml
Labels: lgtm, size/S, cla: yes

#373 fix: Release id typo
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm, cla: yes

#374 fix: Test change log
  .github/scripts/release/create_changelog.sh
  .github/workflows/change-log.yml
Labels: size/M, cla: yes

#375 Fix workflow dependencies
  .github/scripts/release/create_changelog.sh
Labels: size/XS, cla: yes

#376 Fix workflow dependencies
  .github/scripts/release/create_changelog.sh
Labels: size/XS, cla: yes

#378 fix: Create changelog
  .github/scripts/release/create_changelog.sh
  .github/workflows/create-release.yaml
Labels: size/M, lgtm, cla: yes

#388 deps: Bump lifecycle-manager api dependency
  runtime-watcher/go.mod
  runtime-watcher/go.sum
Labels: lgtm, size/S, cla: yes

#390 chore: Use --skr-watcher-image-registry flag to configure registry
  .github/actions/patch-lifecycle-manager/action.yaml
Labels: size/XS, lgtm, cla: yes
