Repository kyma-project/runtime-watcher, pull requests merged in 2025-03, with the labels that each got.

#501 chore: Update security scanners config for checkmarxone migration
  sec-scanners-config.yaml
Labels: size/S, cla: yes

#503 chore: Add "contents: write" Permission to Create Release Workflow
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm

#509 chore: Add id-token WRITE to Create Release workflow
  .github/workflows/create-release.yaml
Labels: size/XS, lgtm

#512 chore: Bump scanner version to latest release
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#502 chore: Add Watcher Setup guide
  README.md
  docs/Listener.md
  docs/architecture.md
  docs/internal/how_to_release.md
  docs/listener.md
  docs/watcher-setup-guide.md
Labels: area/documentation, size/L
