Repository kyma-project/runtime-watcher, pull requests merged in 2025-02, with the labels that each got.

#475 feat: Add grouping to `dependabot` PRs
  .github/dependabot.yml
Labels: size/M, cla: yes

#485 chore: Bump golangci lint and action
  .github/workflows/pull-listener-pkg.yml
  .github/workflows/pull-runtime-watcher.yml
  listener/.golangci.yaml
  listener/Makefile
  listener/pkg/event/http_test.go
  runtime-watcher/.golangci.yaml
  runtime-watcher/Makefile
  runtime-watcher/internal/cacertificatehandler/ca_certificate_handler_test.go
  runtime-watcher/internal/handler_suite_test.go
  runtime-watcher/tests/e2e/e2e_suite_test.go
Labels: lgtm, size/S, cla: yes

#492 chore: Bump sec-scanners config
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes
